# Generated by Django 4.0.4 on 2022-05-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
    ]
